
name = 'example-worker'
main = 'src/index.ts'
compatibility_date = '2024-01-01'
compatibility_flags = [
  'nodejs_compat',
]
d1_databases = [
  { binding = 'DB', database_name = 'example-db', database_id = 'example-db-dev' },
]
env.development.name = 'example-worker-dev'
env.production.name = 'example-worker-prod'
